### ISSUE TITLE
Direct binder link

### ISSUE THREAD

**Issue by fonsp** [msaroufim/multiple_dispatch#1]
This is awesome!

If you go to https://pluto-on-binder.glitch.me/ and enter a notebook link then you can _right click the resulting link an share it_ directly, so that others can skip those steps!

**Comment by fonsp** [comment]
So:

https://mybinder.org/v2/gh/fonsp/vscode-binder/master?urlpath=pluto/open?url=https%3A%2F%2Fraw.githubusercontent.com%2Fmsaroufim%2Fmultiple_dispatch%2Fmaster%2Fsrc%2Fmultiple_dispatch.jl

**Comment by msaroufim** [comment]
Thank you for following up @fonsp - you're the one making an awesome product

It's a good sign that even after publishing this post I keep thinking of whether I've actually used all the features of Pluto that I could to make the interactivity even better
